# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 53b73509bbe95d1da0219779de425f4c132ec3b1e7f5cd62f6bf9c13f41370e77d04da9b103caaf498ff84c87702422ce1e5ac4cfbb63e03c302e16b57d3fe09

test:
  secret_key_base: 187d151217cd5462c5b8a148972a8df0ab1d4e2e2806377b029c18a68663e8851f59b67ee3e5dfb70d546028295de6df10b331751eddd6a2fb1245feeb039ba2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
